services:
  db:
    image: postgres:15-alpine 
    container_name: easy_book_db
    environment:
      POSTGRES_USER: ${DB_USER}  # Referencia a las variables de entorno
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data  # Persistencia de datos

volumes:
  db_data:
