services:
  app:
    container_name: easy_book_be
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      /bin/sh -c "./wait-for-it.sh db:${DB_PORT} -- yarn migrate:run && yarn start"
    depends_on:
      - db
    networks:
      - easy_book_network

  db:
    image: postgres:15-alpine 
    container_name: easy_book_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - easy_book_network

volumes:
  db_data:

networks:
  easy_book_network:
    driver: bridge
